apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadence
  template:
    metadata:
      labels:
        app: cadence
    spec: 
      containers:
        - name: cadence
          image: ubercadence/server:master-auto-setup
          ports:
            - name: port-8000
              containerPort: 8000
              protocol: TCP
            - name: port-8001
              containerPort: 8001
              protocol: TCP
            - name: port-8002
              containerPort: 8002
              protocol: TCP
            - name: port-8003
              containerPort: 8003
              protocol: TCP
            - name: port-7933
              containerPort: 7933
              protocol: TCP
            - name: port-7934
              containerPort: 7934
              protocol: TCP
            - name: port-7935
              containerPort: 7935
              protocol: TCP
            - name: port-7939
              containerPort: 7939
              protocol: TCP
            - name: port-7833
              containerPort: 7833
              protocol: TCP
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PROMETHEUS_ENDPOINT_0
              value: 0.0.0.0:8000
            - name: PROMETHEUS_ENDPOINT_1
              value: 0.0.0.0:8001
            - name: PROMETHEUS_ENDPOINT_2
              value: 0.0.0.0:8002
            - name: PROMETHEUS_ENDPOINT_3
              value: 0.0.0.0:8003
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/development.yaml
            - name: LOG_LEVEL
              value: debug
            - name: PRIMARY_FRONTEND_SERVICE
              value: cadence-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: BIND_ON_IP
              value: "0.0.0.0"

---
apiVersion: v1
kind: Service
metadata:
  name: cadence-service
spec:
  selector:
    app: cadence
  ports:
    - name: port-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: port-8001
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: port-8002
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: port-8003
      protocol: TCP
      port: 8003
      targetPort: 8003
    - name: port-7933
      protocol: TCP
      port: 7933
      targetPort: 7933
    - name: port-7934
      protocol: TCP
      port: 7934
      targetPort: 7934
    - name: port-7935
      protocol: TCP
      port: 7935
      targetPort: 7935
    - name: port-7939
      protocol: TCP
      port: 7939
      targetPort: 7939
    - name: port-7833
      protocol: TCP
      port: 7833
      targetPort: 7833