apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadence-web
  template:
    metadata:
      labels:
        app: cadence-web
    spec:
      containers:
      - name: cadence-web
        image: ubercadence/web:latest
        ports:
        - containerPort: 8088
        env:
        - name: CADENCE_TCHANNEL_PEERS
          value: cadence-service.{{ .Release.Namespace }}.svc.cluster.local:7933
        
---
apiVersion: v1
kind: Service
metadata:
  name: cadence-web-service
spec:
  selector:
    app: cadence-web
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088



