apiVersion: v1
kind: Service
metadata:
  name: cadence-frontend-service
  labels:
    app: cadence
    component: frontend
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: cadence
    component: frontend
  ports:
    - name: rpc
      protocol: TCP
      port: 7933
      targetPort: rpc
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: metrics
    - name: port-7833
      protocol: TCP
      port: 7833
      targetPort: port-7833
---
{{- range $service := (list "history" "matching" "worker") }}
apiVersion: v1
kind: Service
metadata:
  name: cadence-{{ $service }}-headless
  labels:
    app: cadence
    component: {{ $service }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: cadence
    component: {{ $service }}
  ports:
    - name: rpc
      protocol: TCP
      port: {{ if eq $service "history" }}7934{{ else if eq $service "matching" }}7935{{ else }}7939{{ end }}
      targetPort: rpc
    - name: metrics
      protocol: TCP
      port: {{ if eq $service "history" }}8001{{ else if eq $service "matching" }}8002{{ else }}8003{{ end }}
      targetPort: metrics
   {{- if eq $service "history" }}
    - name: grpc-port
      protocol: TCP
      port: 7834
      targetPort: grpc-port
   {{- end }}
---
{{- end }}
