apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadence.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  dynamic_config.yaml: |-
    {{- toYaml .Values.dynamicConfig.values | nindent 12 }}
