 
dynamicConfig:
  values:
    history.workflowIDExternalRateLimitEnabled:
      - value: true

log:
  stdout: true
  level: "info"

cassandra:
  serviceName: "cassandra-service"
  namespace: "cadence"
  seeds: "cassandra-service.cadence.svc.cluster.local"
  image:
    repository: "cassandra"
    tag: "4.1.1"

image:
  repository: "docker.io/ubercadence/server"
  tag: "master-auto-setup"

deployment:
  replicaCount: 1
  cpu:
    limit: "1000m"  
    request: "500m"  
  memory:
    limit: "2Gi" 
    request: "1Gi"  
  configPath: config/dynamicconfig/development.yaml
  enableES: false 
  skipSchemaSetup: true

