{{- if .Values.cassandra.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  labels:
    {{- include "cadence.commonlabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: {{ .Values.cassandra.deployment.image.repository }}:{{ .Values.cassandra.deployment.image.tag }}
        ports:
        - containerPort: 9042
        env:
        - name: MAX_HEAP_SIZE
          value: "512M"
        - name: HEAP_NEWSIZE
          value: "256M"
        resources:
          limits:
            cpu: {{ .Values.cassandra.deployment.cpu.limit }}
            memory: {{ .Values.cassandra.deployment.memory.limit }}
          requests:
            cpu: {{ .Values.cassandra.deployment.cpu.request }}
            memory: {{ .Values.cassandra.deployment.memory.request }}
        readinessProbe:
          exec:
            command: ["sh", "-c", "cqlsh $(hostname -i) -u cassandra -p cassandra -e 'describe keyspaces'"]
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 30
          failureThreshold: 10
        livenessProbe:
          exec:
            command: ["sh", "-c", "cqlsh $(hostname -i) -u cassandra -p cassandra -e 'describe keyspaces'"]
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 30
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
{{- end }}
