apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadence.fullname" . }}-configmap
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  dynamic_config.yaml: |-
    {{- if .Values.dynamicConfig.values }}
    {{- toYaml .Values.dynamicConfig.values | nindent 4 }}
    {{- else }}
    # Default dynamic configuration - empty config is valid
    {}
    {{- end }}