{{- range $serviceName := (list "frontend" "history" "matching" "worker") }}
{{- $service := index $.Values $serviceName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-headless
  labels:
    {{- include "cadence.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "cadence.serviceLabels" (dict "serviceName" $serviceName "Values" $.Values "Chart" $.Chart "Release" $.Release) | indent 4 }}
  ports:
    - name: rpc
      protocol: TCP
      port: {{ $service.port }}
      targetPort: rpc
    {{- if ne $serviceName "worker" }}
    - name: grpc
      protocol: TCP
      port: {{ $service.grpcPort }}
      targetPort: grpc
    {{- end }}
    {{- if $.Values.metrics.enabled }}
    - name: {{ $.Values.metrics.portName | default "metrics" }}
      protocol: TCP
      port: {{ $.Values.metrics.port | default 9090 }}
      targetPort: {{ $.Values.metrics.portName | default "metrics" }}
    {{- end }}
{{- end }}