{{- range $serviceName := (list "frontend" "history" "matching" "worker") }}
{{- $service := index $.Values $serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "cadence.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  replicas: {{ $service.replicas }}
  {{- with $service.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cadence.serviceLabels" (dict "serviceName" $serviceName "Values" $.Values "Chart" $.Chart "Release" $.Release) | indent 6 }}
  template:
    metadata:
      {{- $servicePodAnnotations := $service.podAnnotations | default dict }}
      {{- if $servicePodAnnotations }}
      annotations:
        {{- toYaml $servicePodAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cadence.labels" $ | nindent 8 }}
        {{- with $service.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: {{ $serviceName }}
    spec:
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "cadence.serviceAccountName" $ }}
      {{- end }}
      {{- $globalImagePullSecrets := $.Values.global.imagePullSecrets | default list }}
      {{- $serviceImagePullSecrets := $service.image.imagePullSecrets | default list }}
      {{- $mergedImagePullSecrets := concat $globalImagePullSecrets $serviceImagePullSecrets }}
      {{- if $mergedImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $mergedImagePullSecrets | nindent 8 }}
      {{- end }}
      {{- $globalPriorityClassName := $.Values.global.priorityClassName | default "" }}
      {{- $servicePriorityClassName := $service.priorityClassName | default $globalPriorityClassName }}
      {{- if $servicePriorityClassName }}
      priorityClassName: {{ $servicePriorityClassName }}
      {{- end }}
      {{- $globalPodSecurityContext := $.Values.global.podSecurityContext | default dict }}
      {{- $servicePodSecurityContext := $service.podSecurityContext | default $globalPodSecurityContext }}
      {{- if $servicePodSecurityContext }}
      securityContext:
        {{- toYaml $servicePodSecurityContext | nindent 8 }}
      {{- end }}
      {{- $globalNodeSelector := $.Values.global.nodeSelector | default dict }}
      {{- $serviceNodeSelector := $service.nodeSelector | default $globalNodeSelector }}
      {{- if $serviceNodeSelector }}
      nodeSelector:
        {{- toYaml $serviceNodeSelector | nindent 8 }}
      {{- end }}
      {{- $globalAffinity := $.Values.global.affinity | default dict }}
      {{- $serviceAffinity := $service.affinity | default $globalAffinity }}
      {{- if $serviceAffinity }}
      affinity:
        {{- toYaml $serviceAffinity | nindent 8 }}
      {{- end }}
      {{- $globalTolerations := $.Values.global.tolerations | default list }}
      {{- $serviceTolerations := $service.tolerations | default $globalTolerations }}
      {{- if $serviceTolerations }}
      tolerations:
        {{- toYaml $serviceTolerations | nindent 8 }}
      {{- end }}
      {{- $globalTopologySpreadConstraints := $.Values.global.topologySpreadConstraints | default list }}
      {{- $serviceTopologySpreadConstraints := $service.topologySpreadConstraints | default $globalTopologySpreadConstraints }}
      {{- if $serviceTopologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml $serviceTopologySpreadConstraints | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-schema
        {{- $dbDriver := $.Values.config.persistence.database.driver }}
        {{- if eq $dbDriver "cassandra" }}
        image: {{ $.Values.schema.checkSchema.cassandra.image.repository }}:{{ $.Values.schema.checkSchema.cassandra.image.tag }}
        imagePullPolicy: {{ $.Values.schema.checkSchema.cassandra.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            # Create .cassandra directory for cqlshrc if it doesn't exist
            mkdir -p ~/.cassandra

            # Build cqlshrc configuration file
            cat > ~/.cassandra/cqlshrc << EOF
            [connection]
            hostname = $DB_HOST
            port = $DB_PORT

            EOF

            # Add authentication section if user is provided
            if [ -n "$DB_USER" ] && [ "$DB_USER" != "" ]; then
              cat >> ~/.cassandra/cqlshrc << EOF
            [authentication]
            username = $DB_USER
            EOF
              # Add password if provided
              if [ -n "$CASSANDRA_PASSWORD" ] && [ "$CASSANDRA_PASSWORD" != "" ]; then
                cat >> ~/.cassandra/cqlshrc << EOF
            password = $CASSANDRA_PASSWORD
            EOF
                  fi
                fi

            # Add SSL configuration if enabled
            if [ "$TLS_ENABLED" = "true" ]; then
              cat >> ~/.cassandra/cqlshrc << EOF

            [ssl]
            EOF
              # Add certificate file if specified (CA certificate)
              if [ -n "$SSL_CERTFILE" ] && [ "$SSL_CERTFILE" != "" ]; then
                cat >> ~/.cassandra/cqlshrc << EOF
            certfile = $SSL_CERTFILE
            EOF
              fi
              
              # Add client certificate for mutual TLS
              if [ -n "$SSL_CLIENT_CERT" ] && [ "$SSL_CLIENT_CERT" != "" ]; then
                cat >> ~/.cassandra/cqlshrc << EOF
            usercert = $SSL_CLIENT_CERT
            EOF
              fi
              
              # Add client private key for mutual TLS
              if [ -n "$SSL_CLIENT_KEY" ] && [ "$SSL_CLIENT_KEY" != "" ]; then
                cat >> ~/.cassandra/cqlshrc << EOF
            userkey = $SSL_CLIENT_KEY
            EOF
              fi
              
              # Add validate setting
              if [ -n "$SSL_VALIDATE" ] && [ "$SSL_VALIDATE" != "" ]; then
                cat >> ~/.cassandra/cqlshrc << EOF
            validate = $SSL_VALIDATE
            EOF
              else
                cat >> ~/.cassandra/cqlshrc << EOF
            validate = true
            EOF
              fi
            fi

            # Debug: Show generated cqlshrc (remove in production)
            echo "Generated cqlshrc:"
            cat ~/.cassandra/cqlshrc
            echo "---"

            # Build cqlsh command
            build_cqlsh_cmd() {
              local cmd="cqlsh"
              
              # Add SSL option if enabled
              if [ "$TLS_ENABLED" = "true" ]; then
                cmd="$cmd --ssl"
              fi
              
              echo "$cmd"
            }

            # Compare database version with cadence schema version
            until $(build_cqlsh_cmd) -e "
              USE $DB_NAME;
              SELECT curr_version FROM schema_version WHERE keyspace_name = '$DB_NAME';" | grep -q "$DEFAULT_VERSION" &&
              $(build_cqlsh_cmd) -e "
              USE $DB_VISIBILITY_NAME;  
              SELECT curr_version FROM schema_version WHERE keyspace_name = '$DB_VISIBILITY_NAME';" | grep -q "$VISIBILITY_VERSION"
            do
              echo 'Waiting for Cassandra schema to be ready...'
              sleep 10
            done
        env:
        # Schema version parameters
        - name: DEFAULT_VERSION
          value: {{ $.Values.schema.version.default | quote }}
        - name: VISIBILITY_VERSION
          value: {{ $.Values.schema.version.visibility | quote }}
        # Basic connection parameters
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.cassandra.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.cassandra.port | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.cassandra.keyspace | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.cassandra.visibilityKeyspace | quote }}
        # Authentication parameters (conditional)
        {{- if $.Values.config.persistence.database.cassandra.user }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.cassandra.user | quote }}
        {{- end }}
        {{- if $.Values.config.persistence.database.cassandra.password }}
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
              key: CASSANDRA_PASSWORD
        {{- end }}
        # TLS Configuration
        - name: TLS_ENABLED
          value: {{ $.Values.config.persistence.database.cassandra.tls.enabled | quote }}
        {{- if $.Values.config.persistence.database.cassandra.tls.enabled }}
        # SSL_CERTFILE environment variable (CA certificate)
        {{- if $.Values.config.persistence.database.cassandra.tls.caFile }}
        - name: SSL_CERTFILE
          value: {{ $.Values.config.persistence.database.cassandra.tls.caFile | quote }}
        {{- else if $.Values.config.persistence.database.cassandra.tls.caFiles }}
        - name: SSL_CERTFILE
          value: {{ index $.Values.config.persistence.database.cassandra.tls.caFiles 0 | quote }}
        {{- end }}
        # Client certificate for mutual TLS
        {{- if $.Values.config.persistence.database.cassandra.tls.certFile }}
        - name: SSL_CLIENT_CERT
          value: {{ $.Values.config.persistence.database.cassandra.tls.certFile | quote }}
        {{- end }}
        # Client private key for mutual TLS
        {{- if $.Values.config.persistence.database.cassandra.tls.keyFile }}
        - name: SSL_CLIENT_KEY
          value: {{ $.Values.config.persistence.database.cassandra.tls.keyFile | quote }}
        {{- end }}
        # SSL_VALIDATE environment variable
        - name: SSL_VALIDATE
          value: {{ $.Values.config.persistence.database.cassandra.tls.enableHostVerification | quote }}
        {{- end }}
        volumeMounts:
        {{- with $.Values.global.tls.volumeMounts }}
        {{- toYaml . | nindent 2 }}
        {{- end }}
        {{- else if eq $dbDriver "postgres" }}
        image: {{ $.Values.schema.checkSchema.postgres.image.repository }}:{{ $.Values.schema.checkSchema.postgres.image.tag }}
        imagePullPolicy: {{ $.Values.schema.checkSchema.postgres.image.pullPolicy }}
        command:
        - sh
        - -c
        - |
          # Extract schema version.
          file="/etc/cadence/schema/postgres/version.go"
          version=$(grep 'const Version' "$file" | awk -F'"' '{print $2}')
          visibility_version=$(grep 'const VisibilityVersion' "$file" | awk -F'"' '{print $2}')

          # Check schema version in database.
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME; do
            echo 'Waiting for PostgreSQL to be ready...';
            sleep 5;
          done;
          until PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c \"
            SELECT version FROM schema_version WHERE db_name = 'cadence' ORDER BY version DESC LIMIT 1;\" &&
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_VISIBILITY_NAME -c \"
            SELECT version FROM schema_version WHERE db_name = 'cadence_visibility' ORDER BY version DESC LIMIT 1;\";
          do
            echo 'Waiting for PostgreSQL schema setup...';
            sleep 10;
          done"]
        env:
        # Schema version parameters
        - name: DEFAULT_VERSION
          value: {{ $.Values.schema.version.default | quote }}
        - name: VISIBILITY_VERSION
          value: {{ $.Values.schema.version.visibility | quote }}
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.sql.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.postgres.port | default $.Values.config.persistence.database.sql.port | default 5432 }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.sql.user | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.sql.dbname | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.sql.visibilityDbname | quote }}
        {{- else if eq $dbDriver "mysql" }}
        image: {{ $.Values.schema.checkSchema.mysql.image.repository }}:{{ $.Values.schema.checkSchema.mysql.image.tag }}
        imagePullPolicy: {{ $.Values.schema.checkSchema.mysql.image.pullPolicy }}
        command:
        - sh
        - -c
        - |
          # Extract schema version.
          file="/etc/cadence/schema/mysql/version.go"
          version=$(grep 'const Version' "$file" | awk -F'"' '{print $2}')
          visibility_version=$(grep 'const VisibilityVersion' "$file" | awk -F'"' '{print $2}')

          # Check schema version in database.
          until mysqladmin ping -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD --silent; do
            echo 'Waiting for MySQL to be ready...';
            sleep 5;
          done;
          until mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME -e \"
            SELECT version FROM schema_version WHERE db_name = 'cadence' ORDER BY version DESC LIMIT 1;\" &&
          mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_VISIBILITY_NAME -e \"
            SELECT version FROM schema_version WHERE db_name = 'cadence_visibility' ORDER BY version DESC LIMIT 1;\";
          do
            echo 'Waiting for MySQL schema setup...';
            sleep 10;
          done"]
        env:
        # Schema version parameters
        - name: DEFAULT_VERSION
          value: {{ $.Values.schema.version.default | quote }}
        - name: VISIBILITY_VERSION
          value: {{ $.Values.schema.version.visibility | quote }}
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.sql.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.mysql.port | default $.Values.config.persistence.database.sql.port | default 3306 }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.sql.user | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.sql.dbname | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.sql.visibilityDbname | quote }}
        {{- end }}
        {{- $globalSecrets := $.Values.global.secretEnv | default list }}
        {{- $serviceSecrets := $service.secretEnv | default list }}
        {{- $userSecrets := concat $globalSecrets $serviceSecrets -}}
        {{- include "cadence.databaseSecrets" $ -}}
        {{- $databaseSecrets := $.databaseSecrets | default list -}}
        {{- $mergedSecrets := concat $userSecrets $databaseSecrets -}}
        {{- if $mergedSecrets }}
        envFrom:
        - secretRef:
            name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
        {{- end }}
        volumeMounts:
        {{- with $.Values.global.tls.volumeMounts }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: cadence-{{ $serviceName }}
        {{- $globalImage := $.Values.global.image | default dict }}
        {{- $serviceImage := $service.image | default dict }}
        {{- $repository := $serviceImage.repository | default $globalImage.repository }}
        {{- $tag := $serviceImage.tag | default $globalImage.tag }}
        image: {{ $repository }}:{{ $tag }}
        {{- $pullPolicy := $serviceImage.pullPolicy | default $globalImage.pullPolicy | default "IfNotPresent" }}
        imagePullPolicy: {{ $pullPolicy }}
        {{- $globalContainerSecurityContext := $.Values.global.containerSecurityContext | default dict }}
        {{- $serviceContainerSecurityContext := $service.containerSecurityContext | default $globalContainerSecurityContext }}
        {{- if $serviceContainerSecurityContext }}
        securityContext:
          {{- toYaml $serviceContainerSecurityContext | nindent 10 }}
        {{- end }}
        ports:
        - name: rpc
          containerPort: {{ $service.port }}
          protocol: TCP
        {{- if ne $serviceName "worker" }}
        - name: grpc
          containerPort: {{ $service.grpcPort }}
          protocol: TCP
        {{- end }}
        {{- if $.Values.metrics.enabled }}
        - name: {{ $.Values.metrics.portName | default "metrics" }}
          containerPort: {{ $.Values.metrics.port | default 9090 }}
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/cadence/config/config_template.yaml
          subPath: config_template.yaml
        - name: config
          mountPath: {{ $.Values.config.dynamicConfigFilePath | default "/etc/cadence/config/dynamicconfig/config.yaml" }}
          subPath: dynamic_config.yaml
        {{- with $.Values.global.tls.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: SERVICES
          value: {{ $serviceName }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- $globalLog := $.Values.global.log | default dict }}
        {{- $serviceLog := $service.log | default $globalLog }}
        - name: LOG_LEVEL
          value: {{ $serviceLog.level | default "info" | quote }}
        - name: LOG_STDOUT
          value: {{ $serviceLog.stdout | default true | quote }}
        {{- $globalEnv := $.Values.global.env | default list }}
        {{- $serviceEnv := $service.env | default list }}
        {{- $mergedEnv := concat $globalEnv $serviceEnv }}
        {{- if $mergedEnv }}
        {{- toYaml $mergedEnv | nindent 8 }}
        {{- end }}
        {{- with $service.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "cadence.fullname" $ }}-configmap
      {{- with $.Values.global.tls.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}