{{/*
This template creates secrets for all Cadence Server services (frontend, history, matching, worker)
It only creates secrets if secretEnv is defined for global or individual services
*/}}

{{- $services := list "frontend" "history" "matching" "worker" -}}
{{- $hasGlobalSecrets := .Values.global.secretEnv -}}

{{- range $serviceName := $services -}}
{{- $service := index $.Values $serviceName -}}
{{- $hasServiceSecrets := $service.secretEnv -}}
{{- $globalSecrets := $.Values.global.secretEnv | default list -}}
{{- $serviceSecrets := $service.secretEnv | default list -}}
{{- $mergedSecrets := concat $globalSecrets $serviceSecrets -}}

{{- if $mergedSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
  labels:
    {{- include "cadence.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
type: Opaque
data:
  {{- range $secret := $mergedSecrets }}
  {{- if $secret.value }}
  {{ $secret.name }}: {{ $secret.value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}