{{- range $serviceName := (list "frontend" "history" "matching" "worker") }}
{{- $service := index $.Values $serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "cadence.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  replicas: {{ $service.replicas }}
  {{- with $service.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cadence.serviceLabels" (dict "serviceName" $serviceName "Values" $.Values "Chart" $.Chart "Release" $.Release) | indent 6 }}
  template:
    metadata:
      {{- $servicePodAnnotations := $service.podAnnotations | default dict }}
      {{- if $servicePodAnnotations }}
      annotations:
        {{- toYaml $servicePodAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cadence.labels" $ | nindent 8 }}
        {{- with $service.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: {{ $serviceName }}
    spec:
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "cadence.serviceAccountName" $ }}
      {{- end }}
      {{- $globalImagePullSecrets := $.Values.global.imagePullSecrets | default list }}
      {{- $serviceImagePullSecrets := $service.image.imagePullSecrets | default list }}
      {{- $mergedImagePullSecrets := concat $globalImagePullSecrets $serviceImagePullSecrets }}
      {{- if $mergedImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $mergedImagePullSecrets | nindent 8 }}
      {{- end }}
      {{- $globalPriorityClassName := $.Values.global.priorityClassName | default "" }}
      {{- $servicePriorityClassName := $service.priorityClassName | default $globalPriorityClassName }}
      {{- if $servicePriorityClassName }}
      priorityClassName: {{ $servicePriorityClassName }}
      {{- end }}
      {{- $globalPodSecurityContext := $.Values.global.podSecurityContext | default dict }}
      {{- $servicePodSecurityContext := $service.podSecurityContext | default $globalPodSecurityContext }}
      {{- if $servicePodSecurityContext }}
      securityContext:
        {{- toYaml $servicePodSecurityContext | nindent 8 }}
      {{- end }}
      {{- $globalNodeSelector := $.Values.global.nodeSelector | default dict }}
      {{- $serviceNodeSelector := $service.nodeSelector | default $globalNodeSelector }}
      {{- if $serviceNodeSelector }}
      nodeSelector:
        {{- toYaml $serviceNodeSelector | nindent 8 }}
      {{- end }}
      {{- $globalAffinity := $.Values.global.affinity | default dict }}
      {{- $serviceAffinity := $service.affinity | default $globalAffinity }}
      {{- if $serviceAffinity }}
      affinity:
        {{- toYaml $serviceAffinity | nindent 8 }}
      {{- end }}
      {{- $globalTolerations := $.Values.global.tolerations | default list }}
      {{- $serviceTolerations := $service.tolerations | default $globalTolerations }}
      {{- if $serviceTolerations }}
      tolerations:
        {{- toYaml $serviceTolerations | nindent 8 }}
      {{- end }}
      {{- $globalTopologySpreadConstraints := $.Values.global.topologySpreadConstraints | default list }}
      {{- $serviceTopologySpreadConstraints := $service.topologySpreadConstraints | default $globalTopologySpreadConstraints }}
      {{- if $serviceTopologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml $serviceTopologySpreadConstraints | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-schema
        {{- $globalImage := $.Values.global.image | default dict }}
        {{- $serviceImage := $service.image | default dict }}
        {{- $repository := $serviceImage.repository | default $globalImage.repository }}
        {{- $tag := $serviceImage.tag | default $globalImage.tag }}
        image: {{ $repository }}:{{ $tag }}
        {{- $pullPolicy := $serviceImage.pullPolicy | default $globalImage.pullPolicy | default "IfNotPresent" }}
        imagePullPolicy: {{ $pullPolicy }}
        {{- $dbDriver := $.Values.config.persistence.database.driver }}
        {{- if eq $dbDriver "cassandra" }}
        command: ["sh", "-c", "
          # Extract schema version.
          file="/etc/cadence/schema/cassandra/version.go"
          version=$(grep 'const Version' "$file" | awk -F'"' '{print $2}')
          visibility_version=$(grep 'const VisibilityVersion' "$file" | awk -F'"' '{print $2}')

          # Check schema version in database.
          until cqlsh $DB_HOST $DB_PORT -e \"
            USE cadence;
            SELECT curr_version FROM schema_version WHERE keyspace_name = 'cadence';\" | grep -q {{ $.Values.cassandra.schema.version | default "1.0" }} &&
          cqlsh $DB_HOST $DB_PORT -e \"
            USE cadence_visibility;
            SELECT curr_version FROM schema_version WHERE keyspace_name = 'cadence_visibility';\" | grep -q {{ $.Values.cassandra.schema.visibility_version | default "1.0" }};
          do
            echo 'Waiting for Cassandra schema setup...';
            sleep 10;
          done"]
        env:
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.cassandra.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.cassandra.port | quote }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.cassandra.user | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.cassandra.keyspace | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.cassandra.visibilityKeyspace | quote }}
        {{- else if eq $dbDriver "postgres" }}
        command: ["sh", "-c", "
          # Extract schema version.
          file="/etc/cadence/schema/postgres/version.go"
          version=$(grep 'const Version' "$file" | awk -F'"' '{print $2}')
          visibility_version=$(grep 'const VisibilityVersion' "$file" | awk -F'"' '{print $2}')

          # Check schema version in database.
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME; do
            echo 'Waiting for PostgreSQL to be ready...';
            sleep 5;
          done;
          until PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c \"
            SELECT version FROM schema_version WHERE db_name = 'cadence' ORDER BY version DESC LIMIT 1;\" &&
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_VISIBILITY_NAME -c \"
            SELECT version FROM schema_version WHERE db_name = 'cadence_visibility' ORDER BY version DESC LIMIT 1;\";
          do
            echo 'Waiting for PostgreSQL schema setup...';
            sleep 10;
          done"]
        env:
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.sql.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.postgres.port | default $.Values.config.persistence.database.sql.port | default 5432 }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.sql.user | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.sql.dbname | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.sql.visibilityDbname | quote }}
        {{- else if eq $dbDriver "mysql" }}
        command: ["sh", "-c", "
          # Extract schema version.
          file="/etc/cadence/schema/mysql/version.go"
          version=$(grep 'const Version' "$file" | awk -F'"' '{print $2}')
          visibility_version=$(grep 'const VisibilityVersion' "$file" | awk -F'"' '{print $2}')

          # Check schema version in database.
          until mysqladmin ping -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD --silent; do
            echo 'Waiting for MySQL to be ready...';
            sleep 5;
          done;
          until mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME -e \"
            SELECT version FROM schema_version WHERE db_name = 'cadence' ORDER BY version DESC LIMIT 1;\" &&
          mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_VISIBILITY_NAME -e \"
            SELECT version FROM schema_version WHERE db_name = 'cadence_visibility' ORDER BY version DESC LIMIT 1;\";
          do
            echo 'Waiting for MySQL schema setup...';
            sleep 10;
          done"]
        env:
        - name: DB_HOST
          value: {{ $.Values.config.persistence.database.sql.hosts | quote }}
        - name: DB_PORT
          value: {{ $.Values.config.persistence.database.mysql.port | default $.Values.config.persistence.database.sql.port | default 3306 }}
        - name: DB_USER
          value: {{ $.Values.config.persistence.database.sql.user | quote }}
        - name: DB_NAME
          value: {{ $.Values.config.persistence.database.sql.dbname | quote }}
        - name: DB_VISIBILITY_NAME
          value: {{ $.Values.config.persistence.database.sql.visibilityDbname | quote }}
        {{- end }}
        {{- $globalSecrets := $.Values.global.secretEnv | default list }}
        {{- $serviceSecrets := $service.secretEnv | default list }}
        {{- $mergedSecrets := concat $globalSecrets $serviceSecrets }}
        {{- if $mergedSecrets }}
        envFrom:
        - secretRef:
            name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
        {{- end }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- with $.Values.global.tls.volumeMounts }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: cadence-{{ $serviceName }}
        {{- $globalImage := $.Values.global.image | default dict }}
        {{- $serviceImage := $service.image | default dict }}
        {{- $repository := $serviceImage.repository | default $globalImage.repository }}
        {{- $tag := $serviceImage.tag | default $globalImage.tag }}
        image: {{ $repository }}:{{ $tag }}
        {{- $pullPolicy := $serviceImage.pullPolicy | default $globalImage.pullPolicy | default "IfNotPresent" }}
        imagePullPolicy: {{ $pullPolicy }}
        {{- $globalContainerSecurityContext := $.Values.global.containerSecurityContext | default dict }}
        {{- $serviceContainerSecurityContext := $service.containerSecurityContext | default $globalContainerSecurityContext }}
        {{- if $serviceContainerSecurityContext }}
        securityContext:
          {{- toYaml $serviceContainerSecurityContext | nindent 10 }}
        {{- end }}
        ports:
        - name: rpc
          containerPort: {{ $service.port }}
          protocol: TCP
        {{- if ne $serviceName "worker" }}
        - name: grpc
          containerPort: {{ $service.grpcPort }}
          protocol: TCP
        {{- end }}
        {{- if $.Values.metrics.enabled }}
        - name: {{ $.Values.metrics.portName | default "metrics" }}
          containerPort: {{ $.Values.metrics.port | default 9090 }}
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/cadence/config/config_template.yaml
          subPath: config_template.yaml
        - name: config
          mountPath: {{ $.Values.config.dynamicConfigFilePath | default "/etc/cadence/config/dynamicconfig/config.yaml" }}
          subPath: dynamic_config.yaml
        {{- with $.Values.global.tls.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: SERVICES
          value: {{ $serviceName }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- $globalLog := $.Values.global.log | default dict }}
        {{- $serviceLog := $service.log | default $globalLog }}
        - name: LOG_LEVEL
          value: {{ $serviceLog.level | default "info" | quote }}
        - name: LOG_STDOUT
          value: {{ $serviceLog.stdout | default true | quote }}
        {{- $globalEnv := $.Values.global.env | default list }}
        {{- $serviceEnv := $service.env | default list }}
        {{- $mergedEnv := concat $globalEnv $serviceEnv }}
        {{- if $mergedEnv }}
        {{- toYaml $mergedEnv | nindent 8 }}
        {{- end }}
        {{- $globalSecrets := $.Values.global.secretEnv | default list }}
        {{- $serviceSecrets := $service.secretEnv | default list }}
        {{- $mergedSecrets := concat $globalSecrets $serviceSecrets }}
        {{- if $mergedSecrets }}
        envFrom:
        - secretRef:
            name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
        {{- end }}
        {{- with $service.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "cadence.fullname" $ }}-configmap
      {{- with $.Values.global.tls.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}