{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cadence.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.metrics.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.metrics.serviceMonitor.namespaceSelector | nindent 4 }}
  {{- else }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cadence.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.metrics.portName }}
    interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    {{- if .Values.metrics.serviceMonitor.honorLabels }}
    honorLabels: true
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings: {{ toYaml .Values.metrics.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel | quote }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels: {{ toYaml .Values.metrics.serviceMonitor.targetLabels | nindent 2 }}
  {{- end }}
{{- end }}