{{/*
This template creates secrets for all Cadence Server services (frontend, history, matching, worker)
It creates secrets from secretEnv configuration and automatically adds database/service passwords
*/}}

{{- $services := list "frontend" "history" "matching" "worker" -}}

{{- range $serviceName := $services -}}
{{- $service := index $.Values $serviceName -}}
{{- $globalSecrets := $.Values.global.secretEnv | default list -}}
{{- $serviceSecrets := $service.secretEnv | default list -}}
{{- $userSecrets := concat $globalSecrets $serviceSecrets -}}

{{- /* Call helper to populate database secrets */ -}}
{{- include "cadence.databaseSecrets" $ -}}
{{- $databaseSecrets := $.databaseSecrets | default list -}}

{{- $mergedSecrets := concat $userSecrets $databaseSecrets -}}

{{- if $mergedSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadence.fullname" $ }}-{{ $serviceName }}-secrets
  labels:
    {{- include "cadence.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
type: Opaque
data:
  {{- range $secret := $mergedSecrets }}
  {{- if $secret.value }}
  {{ $secret.name }}: {{ $secret.value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}