{{/*
This template creates secrets only for the web service
It only uses secretEnv defined specifically for the web service (not global)
*/}}

{{- $webSecrets := .Values.web.secretEnv | default list -}}

{{- if $webSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadence.fullname" . }}-web-secrets
  labels:
    {{- include "cadence.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
data:
  {{- range $secret := $webSecrets }}
  {{- if $secret.value }}
  {{ $secret.name }}: {{ $secret.value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}